package com.zt.app.tool.common;

public enum ERROR_CODES {
    SUCCESS,
    INPUT_DIR_INVALID,
    FILE_READ_ERROR,
    INVALID_SRC_FILE,
    TARGET_DIR_INVALID,
    NO_MATCHING_PATTERN,
    NON_VALID_FILE_LIST,
    INVALID_PROJECT_TARGET_FOLDER,
    CREATE_SERVER_PROJECT_DIR_FAILED,
    CREATE_PARENT_PATH_FAILED,
    CREATE_EXPORT_PATH_FAILED,
    INPUT_PARAM_EMPTY,
    INVALID_PROJECT_DIR,
    INVALID_EXPORT_FOLDER,
    FILE_COPY_FAILED,
    EMPTY_RESULT_HOLDER;
}
