package com.zt.app.tool.common;

public enum ERROR_CODES {
    SUCCESS,
    INPUT_DIR_INVALID,
    FILE_READ_ERROR,
    SRC_DIR_INVALID,
    TARGET_DIR_INVALID,
    NO_MATCHING_PATTERN,
    NON_VALID_FILE_LIST,
    INVALID_PROJECT_TARGET_FOLDER,
    CREATE_SERVER_PROJECT_DIR_FAILED,
    FILE_COPY_FAILED;
}
